version: "3.7"

networks:
  0x6flab-jikoni-base-net:
    driver: bridge

volumes:
  0x6flab-jikoni-db-volume:


services:
  jikoni-db:
    image: postgres:13.3-alpine
    container_name: 0x6flab-jikoni-db
    restart: on-failure
    depends_on:
      - jikoni-zipkin
    environment:
      POSTGRES_USER: ${JIKONI_DB_USER}
      POSTGRES_PASSWORD: ${JIKONI_DB_PASS}
      POSTGRES_DB: ${JIKONI_DB}
    ports:
      - ${JIKONI_DB_PORT}:${JIKONI_DB_PORT}
    expose:
      - ${JIKONI_DB_PORT}
    networks:
      - 0x6flab-jikoni-base-net
    volumes:
      - 0x6flab-jikoni-db-volume:/var/lib/postgresql/data
    command: -p ${JIKONI_DB_PORT}

  jikoni-orders:
    image: rodneydav/jikoni-orders:${JIKONI_RELEASE_TAG}
    container_name: jikoni-orders
    restart: on-failure
    depends_on:
      - jikoni-db
      - jikoni-zipkin
    environment:
      JIKONI_LOG_LEVEL: ${JIKONI_LOG_LEVEL}
      JIKONI_DB_HOST: ${JIKONI_DB_HOST}
      JIKONI_DB_PORT: ${JIKONI_DB_PORT}
      JIKONI_DB_USER: ${JIKONI_DB_USER}
      JIKONI_DB_PASS: ${JIKONI_DB_PASS}
      JIKONI_DB: ${JIKONI_DB}
      JIKONI_DB_SSL_MODE: ${JIKONI_DB_SSL_MODE}
      JIKONI_DB_SSL_CERT: ${JIKONI_DB_SSL_CERT}
      JIKONI_DB_SSL_KEY: ${JIKONI_DB_SSL_KEY}
      JIKONI_DB_SSL_ROOT_CERT: ${JIKONI_DB_SSL_ROOT_CERT}
      JIKONI_HTTP_PORT: ${JIKONI_HTTP_PORT}
      JIKONI_SERVER_CERT: ${JIKONI_SERVER_CERT}
      JIKONI_SERVER_KEY: ${JIKONI_SERVER_KEY}
      JIKONI_ZIPKIN_URL: ${JIKONI_ZIPKIN_URL}
    ports:
      - ${JIKONI_HTTP_PORT}:${JIKONI_HTTP_PORT}
    expose:
      - ${JIKONI_HTTP_PORT}
    networks:
      - 0x6flab-jikoni-base-net
  
  jikoni-zipkin:
    image: openzipkin/zipkin
    container_name: jikoni-zipkin
    restart: on-failure
    ports:
      - ${JIKONI_ZIPKIN_PORT}:${JIKONI_ZIPKIN_PORT}
    expose:
      - ${JIKONI_ZIPKIN_PORT}
    networks:
      - 0x6flab-jikoni-base-net

  # fama-prometheus:
  #   image: prom/prometheus
  #   container_name: 0x6flab-jikoni-prometheus
  #   restart: on-failure
  #   depends_on:
  #     - fama-users
  #   ports:
  #     - ${FAMA_PROMETHEUS_PORT}:${FAMA_PROMETHEUS_PORT}
  #   networks:
  #     - 0x6flab-jikoni-base-net      
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # fama-grafana:
  #   image: grafana/grafana
  #   container_name: 0x6flab-jikoni-grafana
  #   restart: on-failure
  #   depends_on:
  #     - fama-prometheus
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=${FAMA_GRAFANA_PASSWORD}      
  #   ports:
  #     - ${FAMA_GRAFANA_PORT}:${FAMA_GRAFANA_PORT}
  #   networks:
  #     - 0x6flab-jikoni-base-net      
  #   volumes:
  #     - 0x6flab-jikoni-grafana-volume:/var/lib/grafana